### ISSUE TITLE
Appears a linter is watching output file

### ISSUE THREAD

**Issue by isaac-martin** [the-couch/slater-theme#3]
Just cloned this down to have a bit of a play with it, appears a linter / wepback is causing thousands of errors on the webpack output file. Not sure if its something in latest version of webpack / babel etc

**Comment by isaac-martin** [comment]
Don't worry, changed some config and all working fine

**Comment by iamkevingreen** [comment]
@isaac-martin mind sharing what you were running into? @estrattonbailey is abstracting some of the slater-tools out of this theme to make the theme less opinionated.

**Comment by isaac-martin** [comment]
Yep, so cloning repo down. Set up API keys etc can all work fine.
Run the command `npm run watch:assets` produces the following output. 

![image](https://user-images.githubusercontent.com/8649366/45053921-71a4be00-b059-11e8-8d56-956d0c61ee47.png)

I changed my loader to be eslint loader and then set it to `extend:standard` in the eslint config file. 
Then ignored `index.js` and `compiled.bundle.js` 

Not sure if that is the right process. My understanding is because they are compiled they're going to fail any linting rules we put in place. 
You may have different local settings that are effecting the way your linter is working. Happy to talk more if you think I can help.

**Comment by estrattonbailey** [comment]
@isaac-martin hey! Yeah we're in the process of updating all-of-the-things. This particular repo has become a bit of a frankenstein. 

Our goal with this repo is to pare it back to just liquid files. The build toolkit is now over at [@slater/cli](https://github.com/the-couch/slater-cli). Basically, I would recommend getting set up with @slater/cli for building/watching/updating the remote site, and using whatever theme file base you want.

I've spent a few days on @slater/cli last over the last few weeks, so if you end up going that route, let us know how it goes! Would love to get that repo tightened up.

**Comment by iamkevingreen** [comment]
This should no longer be happening as we shift into the new slater/cli + rollup and new structure
